name: CountdownAPI
main: io.github.scroojalix.countdownapi.Main
version: ${project.version}
author: Scroojalix
api-version: "1.13"
permission-message: &noperms "\u00A7cYou do not have permission to use this command."
depend: [PlaceholderAPI]

commands:
  begindebugcountdown:
    aliases: [begindebugcount]
    description: "Start the debug countdown timer."
    permission: countdown.begincount
    permission-message: *noperms